update 5.0.0

diff --git a/otl b/otl
--- a/otl
+++ b/otl
@@ -1,171 +1,90 @@
 #!/bin/sh
 
+# shellcheck disable=SC2046
+OTL_HOME="$(dirname $(dirname "$0"))"
 OTL_START="${OTL_HOME}/run-tool/bin/otl"
-SYSTEM_PATH="${OTL_HOME}/system.otls"
 
-# shellcheck disable=SC2039 disable=SC2162
-JAR_FILES=("${OTL_HOME}/analyzer")
-if [ -f "$SYSTEM_PATH" ]; then
-  MODE=""
-  # shellcheck disable=SC2162 disable=SC2039
-  while read line || [ -n "$line" ]; do
-    if [ -z "$line" ] || [[ $line == \#* ]]; then
-      continue
-    elif [[ $line == *: ]]; then
-      MODE="${line:0:(${#line}-1)}"
-    elif [ -n "$MODE" ]; then
-      JAR_FILES+=("${OTL_HOME}/module/${MODE}/${line}")
-    fi
-  done < "$SYSTEM_PATH"
-fi
-# shellcheck disable=SC2039
-JAR_PATH=$(IFS=: ; echo "${JAR_FILES[*]}")
-
-# shellcheck disable=SC2039 disable=SC2162 disable=SC2059 disable=SC2039
-uninstall() {
-  read -p "Are you sure you want to delete it? (y/n) : " DELETE_CHECK
-  if [ "$DELETE_CHECK" != "y" ]; then
-    echo "삭제를 취소합니다."
-    exit 0
-  fi
-  case $SHELL in
-    "/bin/bash"|*bash*)
-      ALIAS=~/.bashrc
-      ;;
-    "/bin/zsh"|*zsh*)
-      ALIAS=~/.zshrc
-      ;;
-    *)
-      printf "${SHELL} - "
-      echo "지원하지 않는 Shell 입니다."
-      exit 0
-      ;;
-  esac
-  case ${OSTYPE} in
-    linux-gnu*)   # linux
-      sed -i '/alias otl/d' $ALIAS
-      sed -i '/export OTL_HOME/d' $ALIAS
-      rm -rf "$OTL_HOME"
-      echo "삭제가 완료되었습니다."
-      ;;
-    darwin*)      # mac
-      sed -i '' '/alias otl/d' $ALIAS
-      sed -i '' '/export OTL_HOME/d' $ALIAS
-      rm -rf "$OTL_HOME"
-      echo "삭제가 완료되었습니다."
-      ;;
-    *)
-      echo "지원하지 않는 OS 입니다."
-      exit 0
-      ;;
-  esac
+abort() {
+  printf "%s\n" "$@" >&2
+  exit 1
 }
 
-# shellcheck disable=SC2006 disable=SC2162 disable=SC2039
-sub_download() {
-  READ_HTTP="$(wget https://raw.githubusercontent.com/OTLanguage/module/main/"${1}"/system.otls -q -O -)"
-  if [ -z "${READ_HTTP}" ]
-  then
-    echo "${1}는 존재하지 않는 모듈입니다."
-    exit 0
-  fi
+finish() {
+  printf "%s\n" "$@" >&2
+  exit 0
+}
 
-  TYPE=""
-  FILE_CONTENT=""
-  if [[ `cat "${OTL_HOME}/system.otls"` == *${1}:* ]]; then
-    CHECK=""
-    while read line || [ -n "$line" ] ; do
-      if [ -z "$line" ]; then
-        continue
-      elif [[ "$line" == *: ]]; then
-        if [[ "$line" == ${1}: ]]; then
-          CHECK="1"
-        else
-          CHECK=""
-          FILE_CONTENT+="${line}${IFS}"
-        fi
-      elif [ "${CHECK}" = "" ]; then
-        FILE_CONTENT+="    ${line}${IFS}"
-      fi
-    done < "${OTL_HOME}/system.otls"
+fileFind() {
+  if ! [ -f "${1}" ]; then
+    abort "The '$(basename "${1}")' file could not be found"
+  fi
+}
+
+fileRead() {
+  if ! [ -r "${1}" ]; then
+    abort "Unable to read the '$(basename "${1}")' file"
+  fi
+}
+
+findJar() {
+  if ! [ -d "${OTL_HOME}/${1}" ]; then
+    abort "The '${1}' module was not found"
+  fi
+  echo "${OTL_HOME}/${1}/*.jar"
+}
+
+# shellcheck disable=SC2006 disable=SC2039
+version() {
+  if [ ${#@} = 1 ]; then
+    abort "option error"
   else
-    FILE_CONTENT=$(<"${OTL_HOME}/system.otls")
+    finish "OTLanguage version " `${OTL_START} -Dfile.encoding=UTF-8 -classPath "${JAR_PATH[0]}" Main "${1}"`
   fi
-
-  rm -rf "${OTL_HOME}/analyzer/cos/${1}"
-  rm -rf "${OTL_HOME}/module/${1}"
-  FILE_CONTENT+="${IFS}${1}:${IFS}"
-  for line in ${READ_HTTP}
-  do
-    if [[ "$line" == *: ]]; then
-      TYPE="${line:0:${#line}-1}"
-    elif [ -z "$TYPE" ] || [ -z "$line" ]; then
-      continue
-    else
-      case "$TYPE" in
-        "class")
-          FILE_PATH="${OTL_HOME}"/analyzer/cos/$(echo "$line" | sed -e "s/~/\//g")
-          FILE_NAME=$(basename "$FILE_PATH")
-          DOWNLOAD_PATH="${FILE_PATH:0:${#FILE_PATH}-${#FILE_NAME}-1}"
-          wget https://github.com/OTLanguage/module/raw/main/"${1}"/"${FILE_NAME}" -P "${DOWNLOAD_PATH}"
-          ;;
-
-        "jar")
-          FILE_PATH="${OTL_HOME}/module/${1}/${line}"
-          FILE_NAME=$(basename "$FILE_PATH")
-          DOWNLOAD_PATH="${FILE_PATH:0:${#FILE_PATH}-${#FILE_NAME}-1}"
-          wget https://github.com/OTLanguage/module/raw/main/"${1}"/"${FILE_NAME}" -P "${DOWNLOAD_PATH}"
-          FILE_CONTENT+="    ${FILE_NAME}${IFS}"
-          ;;
-
-        "other")
-          FILE_PATH="${OTL_HOME}/module/${1}/${line}"
-          FILE_NAME=$(basename "$FILE_PATH")
-          DOWNLOAD_PATH="${FILE_PATH:0:${#FILE_PATH}-${#FILE_NAME}-1}"
-          wget https://github.com/OTLanguage/module/raw/main/"${1}"/"${FILE_NAME}" -P "${DOWNLOAD_PATH}"
-          ;;
-      esac
-    fi
-  done
-  echo "${FILE_CONTENT}" > "${OTL_HOME}/system.otls"
 }
 
-add_download() {
-  EXT="$(wget https://raw.githubusercontent.com/OTLanguage/module/main/"${1}"/add.otls -q -O -)"
-  FILE_NAME="${2}${EXT}"
-  rm "${OTL_HOME}/module/${1}/${FILE_NAME}"
-  wget https://github.com/OTLanguage/module/raw/main/"${1}"/"${FILE_NAME}" -P "${OTL_HOME}/module/${1}"
-}
+# shellcheck disable=SC2039 disable=SC2034
+case ${#@} in
+  0) ARGS=() ;;
+  1)
+    fileFind "${1}" ; fileRead "${1}"
+    ARGS=("${1}")
+    ;;
+  2)
+    fileFind "${1}" ; fileRead "${1}"
+    ARGS+=("${1}" "${2}")
+    ;;
+  *) abort "Option error" ;;
+esac
 
+fileFind "${OTL_START}"
+if ! [ -x "${OTL_START}" ]; then
+  abort "Unable to execute '$(basename "${OTL_START}")' file."
+fi
 
-# shellcheck disable=SC2039 disable=SC2162 disable=SC2059
-if [ ${#@} = 0 ]; then
-  $OTL_START -classpath "${JAR_PATH}" Main
-elif [[ ${1} == -* ]]; then
+# shellcheck disable=SC2039
+JAR_FILES=("${OTL_HOME}/analyzer")
+
+# shellcheck disable=SC2039 disable=SC2006
+while [ -n "${1}" ]; do
   case "${1}" in
-    "-help"|"-h")
-      echo "    Shell Mode: otl"
-      echo "    File Mode: otl <file>"
-      echo
-      echo "    OTLanguage delete : -remove"
-      echo "                        -rm"
-      echo
-      echo "    Module install : -install <module name>"
-      echo "                       -i <module name>"
-      ;;
-    "-remove"|"-rm") uninstall ;;
-    "-install"|"-i")
-      if [ ${#@} == 3 ]; then
-        EXT="$(wget https://raw.githubusercontent.com/OTLanguage/module/main/"${2}"/add.otls -q -O -)"
-        add_download "${2}" "${3}"
-      else
-        sub_download "${2}"
-      fi
-      ;;
-    *)
-      echo "    OTLanguage information : -help -h"
-      ;;
+    "-version") version "-v" ;;
+    *) break ;;
   esac
+  shift
+done
+
+# shellcheck disable=SC2039 disable=SC2006 disable=SC2207 disable=SC2116
+if [ ${#ARGS[@]} = 0 ]; then
+  for module in `echo "${OTL_HOME}/module/*"` ; do
+    JAR_FILES+=(`findJar "${module}"`)
+  done
+  JAR_PATH=$(IFS=: ; echo "${JAR_FILES[*]}")
+  $OTL_START -Dfile.encoding=UTF-8 -classPath "${JAR_PATH}" Main ""
 else
-  $OTL_START -classpath "${JAR_PATH}" Main "$@"
+  # compile shell
+  for module in `${OTL_START} -Dfile.encoding=UTF-8 -classPath "${JAR_PATH[0]}" Main "-c" "${ARGS[0]}"` ; do
+    JAR_FILES+=(`findJar "${module}"`)
+  done
+  JAR_PATH=$(IFS=: ; echo "${JAR_FILES[*]}")
+  $OTL_START -Dfile.encoding=UTF-8 -classPath "${JAR_PATH}" Main "" "${ARGS[@]}"
 fi
